spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: 452855e0b1e8daa446a06049153e1f69
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - account_email

  redis:
    host: 127.0.0.1
    port: 6379

  login:
    oauth2-password: oauth2-password
    oauth2-redirect-url: /signin/3
    app-home-url: https://yanabada-fe-1r96.vercel.app


jwt:
  secretKey: yanabadaSecretKeyyanabadaSecretKeyyanabadaSecretKey

email:
  host: smtp.gmail.com
  port: 587
  user: tjdtn0219@ajou.ac.kr
  password: wvuh cnxb oizl gnjv

chatroom:
  topic:
    prefix: /sub/chatroom/

firebase:
  project-id: yanabada-b13ee
  key-path: yanabada-firebase-key.json
  fcm-request-url:
    prefix: https://fcm.googleapis.com/v1/projects/
    postfix: /messages:send

s3:
  end-point: https://yanabada-image.s3.ap-northeast-2.amazonaws.com/

